include:
  - board: mwave_33
    artifact-name: ansi-windows-high-sec
  - board: mwave_33
    artifact-name: ansi-mac-high-sec
    cmake-args: -DKEYMAP_FILE=/tmp/zmk-config/config/mwave_33_mac.keymap
  - board: mwave_33
    artifact-name: iso-windows-high-sec
    cmake-args: -DKEYMAP_FILE=/tmp/zmk-config/config/mwave_33_iso.keymap