manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/refil
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: refil
      revision: disable-endpoint-fallback
      import: app/west.yml
    - name: MWave-zephyr-module
      url: git@github.com:PolarityWorks/MWave-zephyr-module.git
      import: config/west.yml
      revision: main
  self:
    path: config